# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](#443F5D)\
$username\
[](bg:#302C43 fg:#443F5D)\
$directory\
[](fg:#302C43 bg:#8A7FB6)\
$git_branch\
$git_status\
[](fg:#8A7FB6 bg:#7BC0E9)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$helm\
$julia\
$nodejs\
$nim\
$rust\
$aws\
[](fg:#7BC0E9 bg:#9AB8F1)\
$docker_context\
[ ](fg:#9AB8F1)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#5C5E84 bg:#443F5D"
style_root = "fg:#5C5E84 bg:#443F5D"
format = '[ $user ]($style)'

[directory]
style = "fg:#5C5E84 bg:#302C43"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"development" = ""
".config" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[docker_context]
symbol = " "
style = "fg:#5C5E84 bg:#9AB8F1"
format = '[[ $symbol $context ](bg:#9AB8F1)]($style) $path'

[elixir]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[elm]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[git_branch]
symbol = ""
style = "fg:#5C5E84 bg:#8A7FB6"
format = '[[ $symbol $branch ](fg:#5C5E84 bg:#8A7FB6)]($style)'

[git_status]
style = "fg:#5C5E84 bg:#8A7FB6"
format = '[[($all_status$ahead_behind )](fg:#5C5E84 bg:#8A7FB6)]($style)'

[golang]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[haskell]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[helm]
symbol = "⎈ "
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'
style = "fg:#5C5E84 bg:#7BC0E9"

[java]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[julia]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[nodejs]
symbol = ""
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[nim]
symbol = " "
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[rust]
symbol = ""
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($version) ](fg:#5C5E84 bg:#7BC0E9)]($style)'

[aws]
symbol = "☁️"
style = "fg:#5C5E84 bg:#7BC0E9"
format = '[[ $symbol ($profile) ](fg:COLOR7 bg:COLOR6)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#5C5E84 bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
