# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](#2E4C63)\
$username\
[](bg:#545669 fg:#2E4C63)\
$directory\
[](fg:#545669 bg:#A56461)\
$git_branch\
$git_status\
[](fg:#A56461 bg:#A1887F)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#A1887F bg:#2A6997)\
$docker_context\
[ ](fg:#2A6997)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#2E4C63"
style_root = "bg:#2E4C63"
format = '[ $user ]($style)'

[directory]
style = "bg:#545669"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"development" = ""
".config" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[docker_context]
symbol = " "
style = "bg:#2A6997"
format = '[[ $symbol $context ](bg:#2A6997)]($style) $path'

[elixir]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[elm]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[git_branch]
symbol = ""
style = "bg:#A56461"
format = '[[ $symbol $branch ](bg:#A56461)]($style)'

[git_status]
style = "bg:#A56461"
format = '[[($all_status$ahead_behind )](bg:#A56461)]($style)'

[golang]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[haskell]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[java]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[julia]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[nodejs]
symbol = ""
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[nim]
symbol = " "
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[rust]
symbol = ""
style = "bg:#A1887F"
format = '[[ $symbol ($version) ](bg:#A1887F)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
