# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](#6A1D42)\
$username\
[](bg:#330B2B fg:#6A1D42)\
$directory\
[](fg:#330B2B bg:#F52574)\
$git_branch\
$git_status\
[](fg:#F52574 bg:#10F3F3)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$helm\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#10F3F3 bg:#A61649)\
$docker_context\
[ ](fg:#A61649)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#143641 bg:#6A1D42"
style_root = "fg:#143641 bg:#6A1D42"
format = '[ $user ]($style)'

[directory]
style = "fg:#143641 bg:#330B2B"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"development" = ""
".config" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[docker_context]
symbol = " "
style = "fg:#143641 bg:#A61649"
format = '[[ $symbol $context ](bg:#A61649)]($style) $path'

[elixir]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[elm]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[git_branch]
symbol = ""
style = "fg:#143641 bg:#F52574"
format = '[[ $symbol $branch ](fg:#143641 bg:#F52574)]($style)'

[git_status]
style = "fg:#143641 bg:#F52574"
format = '[[($all_status$ahead_behind )](fg:#143641 bg:#F52574)]($style)'

[golang]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[haskell]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[helm]
symbol = "⎈ "
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'
style = "fg:#143641 bg:#10F3F3"

[java]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[julia]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[nodejs]
symbol = ""
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[nim]
symbol = " "
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[rust]
symbol = ""
style = "fg:#143641 bg:#10F3F3"
format = '[[ $symbol ($version) ](fg:#143641 bg:#10F3F3)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#143641 bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
