# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](#76C1FF)\
$username\
[](bg:#ff2a6d fg:#76C1FF)\
$directory\
[](fg:#ff2a6d bg:#f887ff)\
$git_branch\
$git_status\
[](fg:#f887ff bg:#05d9e8)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$helm\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#05d9e8 bg:#1afe49)\
$docker_context\
[ ](fg:#1afe49)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#010120 bg:#76C1FF"
style_root = "fg:#010120 bg:#76C1FF"
format = '[ $user ]($style)'

[directory]
style = "fg:#010120 bg:#ff2a6d"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"development" = ""
".config" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[docker_context]
symbol = " "
style = "fg:#010120 bg:#1afe49"
format = '[[ $symbol $context ](bg:#1afe49)]($style) $path'

[elixir]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[elm]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[git_branch]
symbol = ""
style = "fg:#010120 bg:#f887ff"
format = '[[ $symbol $branch ](fg:#010120 bg:#f887ff)]($style)'

[git_status]
style = "fg:#010120 bg:#f887ff"
format = '[[($all_status$ahead_behind )](fg:#010120 bg:#f887ff)]($style)'

[golang]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[haskell]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[helm]
symbol = "⎈ "
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'
style = "fg:#010120 bg:#05d9e8"

[java]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[julia]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[nodejs]
symbol = ""
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[nim]
symbol = " "
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[rust]
symbol = ""
style = "fg:#010120 bg:#05d9e8"
format = '[[ $symbol ($version) ](fg:#010120 bg:#05d9e8)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#010120 bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
