# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](#AE4F53)\
$username\
[](bg:#688B7F fg:#AE4F53)\
$directory\
[](fg:#688B7F bg:#8F7490)\
$git_branch\
$git_status\
[](fg:#8F7490 bg:#BBA5B5)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#BBA5B5 bg:#D9B3B1)\
$docker_context\
[ ](fg:#D9B3B1)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#AE4F53"
style_root = "bg:#AE4F53"
format = '[ $user ]($style)'

[directory]
style = "bg:#688B7F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"development" = ""
".config" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[docker_context]
symbol = " "
style = "bg:#D9B3B1"
format = '[[ $symbol $context ](bg:#D9B3B1)]($style) $path'

[elixir]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[elm]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[git_branch]
symbol = ""
style = "bg:#8F7490"
format = '[[ $symbol $branch ](bg:#8F7490)]($style)'

[git_status]
style = "bg:#8F7490"
format = '[[($all_status$ahead_behind )](bg:#8F7490)]($style)'

[golang]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[haskell]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[java]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[julia]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[nodejs]
symbol = ""
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[nim]
symbol = " "
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[rust]
symbol = ""
style = "bg:#BBA5B5"
format = '[[ $symbol ($version) ](bg:#BBA5B5)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
