# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
format = """
[](#6F54A0)\
$username\
[](bg:#9231A3 fg:#6F54A0)\
$directory\
[](fg:#9231A3 bg:#9F57A4)\
$git_branch\
$git_status\
[](fg:#9F57A4 bg:#CE69DD)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$helm\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#CE69DD bg:#AB5ECE)\
$docker_context\
[ ](fg:#AB5ECE)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#6F54A0"
style_root = "bg:#6F54A0"
format = '[ $user ]($style)'

[directory]
style = "bg:#9231A3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"development" = ""
".config" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[docker_context]
symbol = " "
style = "bg:#AB5ECE"
format = '[[ $symbol $context ](bg:#AB5ECE)]($style) $path'

[elixir]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[elm]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[git_branch]
symbol = ""
style = "bg:#9F57A4"
format = '[[ $symbol $branch ](bg:#9F57A4)]($style)'

[git_status]
style = "bg:#9F57A4"
format = '[[($all_status$ahead_behind )](bg:#9F57A4)]($style)'

[golang]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[haskell]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[helm]
symbol = "⎈ "
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'
style = "bg:#CE69DD"

[java]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[julia]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[nodejs]
symbol = ""
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[nim]
symbol = " "
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[rust]
symbol = ""
style = "bg:#CE69DD"
format = '[[ $symbol ($version) ](bg:#CE69DD)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[[ ♥ $time ](bg:#33658A)]($style)'
